### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by muggel8378** [chgatla-microsoft/QRTracking#11]
I tried to test this kind of qr code tracking. So downloaded it and extract and opend it in Unity. Switching Platform to UWP. Build works, but if I deployed it to Hololens2 I only see the end of blue axis (when I go back a few cm I see the complete coordinate system), but qr-code tracking doesn't work.
Using Unity 2018.4.22f, Hololens2.
Microsoft.MixedReality.QR 0.5.2055-rc (like given in projekt)
MRTK 2.1.0 (like in project)

**Comment by ericalbers** [comment]
Exactly the same for me, blue axis comes right out of my nose on running, can backup and see Axis, but does not track QR code at all.  Unity 2019.4.0f1

**Comment by Dynamike108** [comment]
Had the same problem ... You have to add a "tracked pose driver" to the main camera ... see my new ticket for further info

**Comment by chgatla-microsoft** [comment]
There are lot of new updates Please reopen if you still have the problem
