### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by ericalbers** [chgatla-microsoft/QRTracking#13]
Compiles and runs, axis is placed at head position with blue coming out your eyes, does not track QR codes, logs look like gets exception.
Exception thrown at 0x00007FFD79A839EC in SampleQRCodes.exe: Microsoft C++ exception: Cn::XH at memory location 0x000000BCBCFFD5C0.
onecoreuap\windows\moderncore\inputv2\inputhost\components\cursor\client\cursorclient.cpp(44)\InputHost.dll!00007FFD6EA6D6E4: (caller: 00007FFD6EA6CDEC) ReturnHr(1) tid(b68) 87B20809 onecoreuap\windows\moderncore\inputv2\inputhost\components\cursor\client\cursorclient.cpp(76)\InputHost.dll!00007FFD6EA6CE0C: (caller: 00007FFD790DD37C) ReturnHr(2) tid(b68) 87B20809 'SampleQRCodes.exe' (Win32): Loaded 'C:\Windows\system32\UiaManager.dll'. 
Exception thrown at 0x00007FFD79A839EC in SampleQRCodes.exe: Microsoft C++ exception: Cn::XH at memory location 0x000000BCBCFFD580.

**Comment by andreasanta** [comment]
Same happens to me on first run with no extra settings. Can someone please help?

I'm using Unity 2019.4.8f1.

Thanks

**Comment by chgatla-microsoft** [comment]
The sample is updated to latest Unity 2020. If you see the same issue with the sample please reopen.
