### ISSUE TITLE
Error Namespace 'WindowsMR' does not exist

### ISSUE THREAD

**Issue by axteroide** [chgatla-microsoft/QRTracking#15]
When compiling the scripts I get this error:

SpatialGraphCoordinateSystem.cs(75,60): error CS0234: The type or namespace name 'WindowsMR' does not exist in the namespace 'UnityEngine.XR' (are you missing an assembly reference?)

I have:
Windows 10
Unity: 2018.4.23f1
MRTK: 2.4.0

**Comment by Dynamike108** [comment]
Had the same problem ... try Unity version 2019.4

I still can't get the package to work, but because of a different problem.

**Comment by chgatla-microsoft** [comment]
The latest of this sample is using unity 2019. If you are using older unity there is a fork of the branch.
