### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Dynamike108** [chgatla-microsoft/QRTracking#16]
I've spend way to much time to get it to run...

I'm using Unity 2019.4.9 and there is a current issue with graphics job:
https://issuetracker.unity3d.com/issues/enabling-graphics-jobs-in-2019-dot-3-x-results-in-a-crash-or-nothing-rendering-on-hololens-2
So you have to disable the "Graphics Jobs" option in the player -> other settings

Anyway, the docs should tell you to use the XRSDK Profile and to look at the docs at https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html

From the sample its not clear how the components work, its not working right of the box and you have to do to many adjustments for it to work.

I was making it work with adding the tracked pose driver only to find the docs afterward and it was working with the XRSDK Profile on MRTK

**Comment by Dynamike108** [comment]
MRTK version 2.4.0 was used

**Comment by tmhab** [comment]
What steps were you required to do to make this work?

**Comment by andreasanta** [comment]
I would like to know too please. I have to use legacy VR (because XR Plugin does not work with hands tracking), so I cannot switch to XR SDK.  @Dynamike108 Can you please tell us how you managed to make it work with the Tracked Pose Driver?

**Comment by Zulex** [comment]
Also using unity 2019.4.11 the sample works out of the box compiling for arm64, haven't used any other method. Remote from unity does not work as far as I know in the new XR SDK. (See my ticket) Native on hololens should work straight away.

**Comment by Dynamike108** [comment]
In our project we had to remove the QR Code scanning, because it needs the new XR Plugin, but in the new system the Anchors and WorkdAnchorStore are not working like they used to, so we would have to build everything new.

I haven't found a way to make it work with the legacy VR system.
Btw this is really crap, because Azure Spatial Anchors use the legacy System!
Would be great if Microsoft could get a solution where all parts work together!

To make the sample project work with the new XR Plugin:
- Use the sample project scene
- Got to the MRTK GameObject (where you can set the Profiles) and change to the XRSDK Profile

In the end thats all what was needed, but to find this took me some time.
I'm writing this from memory, but I hope it works out for you.

**Comment by chgatla-microsoft** [comment]
The history of the Project should have different older versions Choose which ever you need, pick from a label and then update just your QR nuget. There is version with XRSDK and legacy, and unity 2019 and unity 2020.
