### ISSUE TITLE
Cached QR Code issues

### ISSUE THREAD

**Issue by Shubham7694** [chgatla-microsoft/QRTracking#2]
The QR once scanned stays in memory. So, when we start scanning, the old QR is thrown in the event. 
How can we distinguish whether the QR is latest or old. The properties of QR Code class are like LastDetectedTime or SystemRelativeLastDetectedTime remain same whether the QR was scanned freshly or it was just retrived from cache.

This has been really painful issue from day 1.

Please guide for any fixes.

Use case:

User need to scan qr to login.
We start QR service and scan and stop the qr service. 
Next time, even without scanning any physical qr, the qr is scanned from memory and login happens.

Currently, i am consuming the scripts and dlls from this repo..

**Comment by chgatla-microsoft** [comment]
The QR codes have a timestamp which should tell when it was last seen so in this specific instance you are interested just reading qrcodes so you should just look at the added/update event. When app starts it gets added events for all the ones in the space and "enumeration complete" event is fired and after that any time a new qrcode is found it is a added event and any qrcode that you visit again is a updated event. From timestamps and the events you should be able to distinguish these.  For your case ignore all qrcodes when you start the app and only process the updated event to see if this is what you are looking for and use it.
