### ISSUE TITLE
Threading issues

### ISSUE THREAD

**Issue by TheRisenPhoenix** [chgatla-microsoft/QRTracking#21]
I'm not sure whether this belongs here or whether I'm doing something incredibly wrong, but I've got some issues related to the events the QRCodeWatcher is firing.
It looks like they are firing from different threads, one thread each per recognized QR Code. 
This leads to a couple of problems in the rest of my code, especially when GameObjects (their MonoBehaviours) are involved and should do something when a QR Code was recognized. Appaerently, methods can only be correctly invoked from within the main thread. 
Is anybody else having these kind of problems? Anyone knows a way around it?

**Comment by Xan2063** [comment]
I can think of 3 ways to solve this:

- In the sample app they use a queue which is filled with QR-Codes by background threads. The items are then picked up in the update of a monobehavior, which is always executed on the main thread
- Schedule the processing on the main thread, either by some helper that remembers the main thread scheduler or the synchronisationContext or some helpers like UnityEngine.WSA.Application.InvokeOnUIThread (not available in the Editor, so a bit awkward to code)
- Use https://github.com/neuecc/UniRx. Convert the events to observables and observe them on the ui thread using the method from UniRx

**Comment by TheRisenPhoenix** [comment]
I solved it similar to your first suggestion. 
I was just wondering whether this is intentional by the library

**Comment by Xan2063** [comment]
I think the qr codes are processed by IO threads where every threads processes a single frame. So I think this is intentional, else you would block the UI thread a lot
