### ISSUE TITLE
Double-byte character hasn't bee supported yet

### ISSUE THREAD

**Issue by meiyg0927** [chgatla-microsoft/QRTracking#35]
**Background:**
We found that If the QR code includes double-byte character (e.g. Chinese, Japanese), the content can't be displayed correctly. 
![image](https://user-images.githubusercontent.com/6658396/113693064-c53f8280-9700-11eb-9242-cb0bdc2fa3b9.png)

**Troubleshooting:**
This bug can be reproduced easily. I pasted a QR code picture below for your test. 
(The link is:  
_https://rd.wechat.com/qrcode/confirm?block_type=101&content=测试&lang=zh_CN&scene=4_ )
![image](https://user-images.githubusercontent.com/6658396/113695249-3ed87000-9703-11eb-933c-921629f04b52.png)

We expect that it will be supported in future. Thanks!

**Comment by chandrasekhar78** [comment]
The platform Qr reader is strict and follows the QR spec 2015. The pasted qrcode above does not specify the encoding mode as "utf8" (assuming it is utf8) and uses default encoding i.e. does not specify any encoding which will be interpreted as IEC 8859-1. If using encoding other than default there should be an ECI specified in the code. Other QR readers might be lenient and can try to predict the encoding so you migh be lucky to see the text. Please use a qr generator that encodes in correct standard.
