### ISSUE TITLE
Can't make it working in a new project

### ISSUE THREAD

**Issue by Thomas-6freedom** [chgatla-microsoft/QRTracking#8]
Hello.
I created a new Unity 2019.2 project.
Added MRTK 2.2.0
Added Nugget for Unity.
Added Microsoft.MixedReality.QR via Nuget for Unity.
Then copied all your /Scripts/ and /Prefabs/ and /Scenes/ folders in my project
Then opened the QRCodesSample.unity, deleted the two MRTK object.
Then MRTK=>Configure Scene
Then build on my HL2.

And the QRCode tracking does not work at all. It does not recognize my QRCode. (The build (made with the same Unity version) of the example project works perfectly with my QRCode).

Do you have an idea why ?

**Comment by Bertrand75014** [comment]
Hi @Thomas-6freedom, 
Did you add _WebCam_ to the project capabilities ?

**Comment by Thomas-6freedom** [comment]
Oh yes I forgot to mention. Yes I did.

**Comment by Bertrand75014** [comment]
And does your application ask for your authorization to access the camera at start ?

**Comment by Thomas-6freedom** [comment]
Yes it did ask. And I accepted of course.

**Comment by Thomas-6freedom** [comment]
I recreated an empty project and its working. My bad.
