### ISSUE TITLE
QR Code Visualizer not handling update correct

### ISSUE THREAD

**Issue by AMollis** [chgatla-microsoft/QRTracking#9]
During a qr code update the visualizer code is assigning the qr code's _instance id_ to the SpatialGraphCoordinateSystem's id.  It should be assigning the qr code's _SpatialGraphNodeId_ to SpatialGraphCoordinateSystem's id.

The bug is in this block of code....

```
else if (action.type == ActionData.Type.Updated)
{
    if (!qrCodesObjectsList.ContainsKey(action.qrCode.Id))
    {
        GameObject qrCodeObject = Instantiate(qrCodePrefab, new Vector3(0, 0, 0), Quaternion.identity);
        qrCodeObject.GetComponent<SpatialGraphCoordinateSystem>().Id = action.qrCode.Id;
        qrCodeObject.GetComponent<QRCode>().qrCode = action.qrCode;
        qrCodesObjectsList.Add(action.qrCode.Id, qrCodeObject);
    }
}
```

**Comment by AMollis** [comment]
Tagging @chgatla-microsoft

**Comment by andreasanta** [comment]
@AMollis It seems to be fixed in the latest version, can you please double check and close? Thanks!

**Comment by andreasanta** [comment]
Submitted PR, hopefully will be merged soon!

**Comment by chgatla-microsoft** [comment]
This is already fixed.
